### ISSUE TITLE
REST request to reset the game 

### ISSUE THREAD

**Issue by bazarum** [luzbel/Temp-VigasocoSDL#1]
We need a REST command to reset to the initial state of the game. 
The endpoint can be something like: 

/cmd/R 
or
/reset

and pass a json with the initial values like: 
{
"pathName": "abadia_<unique _id>", 
"agent": "agentv1",
"model": "abadia_DQN",
"modelVersion": "0.0.1"
"user": "juantomas" 
}
All this values will be stored and we will use it to localize games.

**Comment by luzbel** [comment]
Primera versión https://github.com/luzbel/VigasocoSDL/commit/3a08481b2f8fc4bbe76e296395cc8230690b5323

TODO: Falta ver si hay que limpiar el marcador cuando hay algun mensaje escribiendose para no liar a la IA con un mensaje de la partida anterior

Esta versión aún no acepta un json con valores iniciales

**Comment by bazarum** [comment]
No voy a necesitar los valores iniciales por que parece que tiene mucho más sentido que los mantenga el agente, por que puede y por que los necesita gestionar el.

**Comment by luzbel** [comment]
Estas peticiones se resolverán en el repositorio independiente de la versión optimizada para la IA
en la organización LaAbadIAdelCrimen , ya que no aplican a la versión estándar del juego.

https://github.com/LaAbadIAdelCrimen/VigasocoSDL-AI
