### ISSUE TITLE
create a parameter to control the internal speed of the game

### ISSUE THREAD

**Issue by bazarum** [luzbel/Temp-VigasocoSDL#2]
With this parameter we can play 2x, 5x, 10x or whatever.

**Comment by luzbel** [comment]
asigno a proyecto abadIA

**Comment by luzbel** [comment]
Para probar , modificar https://github.com/luzbel/VigasocoSDL/blob/e38086796a3c94073e433def6906a91aa8fae0cb/VigasocoSDL/SDLTimer.cpp#L24 

Para acelerar 5x, por ejemplo, sería

_ticksPerSecond = calcTicksPerSecond()/5;

@bazarum  Antes de intentar parametrizar esto, ¿puedes probar ese cambio en local y ver que el agente se apaña a jugar a esas velocidades?

**Comment by luzbel** [comment]
Estas peticiones se resolverán en el repositorio independiente de la versión optimizada para la IA
en la organización LaAbadIAdelCrimen , ya que no aplican a la versión estándar del juego.

https://github.com/LaAbadIAdelCrimen/VigasocoSDL-AI
