### ISSUE TITLE
I need a state field with the number of the sound that is playing at the dump command. 

### ISSUE THREAD

**Issue by bazarum** [luzbel/Temp-VigasocoSDL#3]
With this I will training the AI to be more smart about the contextual information, in this case the sound context. Example: when sounds the call for the mass at the chapel.

**Comment by luzbel** [comment]
Estas peticiones se resolverán en el repositorio independiente de la versión optimizada para la IA
en la organización LaAbadIAdelCrimen , ya que no aplican a la versión estándar del juego.

https://github.com/LaAbadIAdelCrimen/VigasocoSDL-AI
