### ISSUE TITLE
I need the text or a unique id of the text displayed

### ISSUE THREAD

**Issue by bazarum** [luzbel/Temp-VigasocoSDL#4]
With this I can training the AI to understand is a different contextual state.

**Comment by luzbel** [comment]
Estas peticiones se resolverán en el repositorio independiente de la versión optimizada para la IA
en la organización LaAbadIAdelCrimen , ya que no aplican a la versión estándar del juego.

https://github.com/LaAbadIAdelCrimen/VigasocoSDL-AI
