### ISSUE TITLE
save/load throw a REST request

### ISSUE THREAD

**Issue by bazarum** [luzbel/Temp-VigasocoSDL#5]
Get all the information needed for save/load using REST request.

the use is something like 

GET /save      --->   <objetcs dump for the restore>
POST /load <objetcs dump for the restore> -----------> restore this exactly state at the game server

**Comment by luzbel** [comment]
Estas peticiones se resolverán en el repositorio independiente de la versión optimizada para la IA
en la organización LaAbadIAdelCrimen

https://github.com/LaAbadIAdelCrimen/VigasocoSDL-AI
